version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  usuarios:
    container_name: usuarios
    build:
      context: ./
      dockerfile: ./usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  cursos:
    container_name: cursos
    build:
      context: ./
      dockerfile: ./cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - usuarios
    restart: always
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring